alphagov/authenticating-proxy

Gemfile, Gemfile.lock, config/initializers/airbrake.rb
This installs the dependencies and sets up an ENV-based configuration.
Additional changes will need to be made to puppet to set these env-vars and also to the hiera data for preview, staging and production.
=> Add airbrake for errbit error reporting

lib/proxy.rb, spec/lib/proxy_spec.rb
The README is out of date and we were doing it wrong. These changes should get it working properly on the draft stack.
=> Correct Rack::Proxy usage

README.md, lib/proxy.rb, spec/requests/proxying_spec.rb
It was setting the User's "id" and not its "uid" from signon, which is not what we want.
=> Fix authentication header

README.md
This makes it clearer how to run authenticating-proxy in the dev VM.
=> Adjust README for running in the dev VM

README.md, config/application.rb, lib/proxy.rb, spec/requests/proxying_spec.rb
This accepts a querystring parameter `token`, consisting of a JWT
containing a subject claim for a fact check id. If the token is valid,
the fact_check_id is passed upstream in the GOVUK_FACT_CHECK_ID header.
Note that this app does not do anything to verify the fact_check_id
itself; that will be done by content-store.
Decoding the token relies on the JWT_AUTH_SECRET env var; the same
value will need to be shared with any publishing app that wants to
generate a token to be used for fact checking.
=> Allow access via JWT for fact checking

lib/proxy.rb, spec/requests/proxying_spec.rb
Frontend apps need to be able to access the encrypted web token so
they can generate viable internal URLs.
I can't see a real need to have the token filtered out at the proxy,
so here we add it back in. It's preferable to sharing the encryption
key with all the frontend apps.
=> Add token to the upstream URL

README.md, lib/proxy.rb, spec/requests/proxying_spec.rb
Content needs to be previewable by users without signon accounts in most stages of a publishers workflow, not just during fact check.
https://trello.com/c/7oRBYwnn/690-rename-fact-check-id-to-auth-bypass-id
=> Rename fact_check_id to auth_bypass_id

Gemfile, Gemfile.lock, lib/proxy.rb, spec/lib/proxy_spec.rb
Trello: https://trello.com/c/cfYVuYnd/242-pre-release-text-files-not-show-full-information
Incorrect content length headers can be returned for content that is
gzipped.
Eg.
```
irb(main):001:0> http = Net::HTTP.new("www.w3.org", 443)
=> #<Net::HTTP www.w3.org:443 open=false>
irb(main):002:0> http.use_ssl = true
=> true
irb(main):003:0> request = Net::HTTP::Get.new("/")
=> #<Net::HTTP::Get GET>
irb(main):004:0> request.initialize_http_header({ "accept-encoding" => "gzip" })
=> {"accept-encoding"=>"gzip"}
irb(main):005:0> response = http.start { http.request(request) }
=> #<Net::HTTPOK 200 OK readbody=true>
irb(main):006:0> response["Content-Length"]
=> "9085"
irb(main):007:0> response.body.bytesize
=> 35437
```
Confusingly if you use `request["accept-encoding"] = "gzip"` above
Net::HTTP …
=> Patch Content-Length header

config/environments/production.rb
This is now provided in [govuk_app_config's configuration](https://github.com/alphagov/govuk_app_config/blob/6f6c398b63585bb368fc54c39d64777022e1665b/lib/govuk_app_config/govuk_logging.rb)
=> Remove app's logging config

config/initializers/gds-sso.rb, spec/requests/sso_spec.rb
With the new external_url_for method in Plek.
=> Explicitly use an external URL for Signon

lib/proxy.rb, spec/requests/proxying_spec.rb
We're working on a new publisher app. Part of that is a page in the publisher that shows the page in mobile and desktop format. To achieve this we'll probably have to iframe pages. Currently this is disallowed by default by Rails. This commit makes sure we strip the `X-Frame-Options` header so iframing becomes allowed again.
https://trello.com/c/QgznZEUJ
=> Allow iframing draft content

lib/proxy.rb, spec/requests/proxying_spec.rb
Trello: https://trello.com/c/dawXVwdW/439-asset-manager-files-are-not-available-when-using-access-tokens-or-if-someone-doesnt-have-asset-manager-permission
This is so that this token can be shared with other apps in the stack,
most notably asset manager. This aims to be the first step to resolving
a problem we have:
- A user can view a draft page with a token
- That page contains draft assets
- Those draft assets can't be viewed because the user is not authenticated.
It uses a cookie for this approach as it would be impractical to append
query strings to every asset in previewing a document.
=> Set auth bypass token into a cookie

db/seeds.rb, lib/proxy.rb, spec/requests/proxying_spec.rb
This is to allow access limiting via a users organisation content-id,
this is part of the work publishing workflow are doing to implement
access limiting. Validation will be done in the content-store on whether a user
belonging to a certain organisation can access a document in the draft stack.
Trello:
https://trello.com/c/wxp1XkSg/969-update-govuk-to-support-access-limiting-by-organisation
=> Set authenticated user organisation header

README.md
Thanks for the explanation, @kevindew (https://github.com/alphagov/authenticating-proxy/pull/158#pullrequestreview-298019994).
`sub` was a point of confusion for me when reading the docs, so knowing that it stands
for "subject" and is one of seven reserved claims is a useful snippet of context to provide here.
=> Explain the `sub` key

README.md
This PR documents the extra information we've had to encode into the auth bypass token of a step by step page (see associated PR [collections-publisher#815](https://github.com/alphagov/collections-publisher/pull/815)).
This is being done in order to accomplish this user story:
> As a editor sharing a fact check link
> I want that link to grant users access to everything the need but only for a reasonable amount of time
> So that the fact checker can't use that credential to dig into
Trello: https://trello.com/c/rjBygcv0/131-create-collections-publisher-authbypasstokens-that-expire-and-have-a-draft-assets-flag
=> Document JWT registered claim names and draft_asset_manager_access

lib/proxy.rb, spec/requests/proxying_spec.rb
This is to allow persisting preview tokens across multiple preview
pages without having to inject preview tokens into all the HTML
links in the page.
Dependent on #163.
Trello: https://trello.com/c/7bauL00z/147-allow-authenticating-proxy-to-read-a-token-from-a-cookie-as-well-as-a-query-string
=> Read auth_bypass_token from cookies if not present in query string

lib/proxy.rb, spec/requests/proxying_spec.rb
If you visit a draft page which your token does not allow access to,
rather than showing a "You do not have permission to view this page"
error, we should redirect the user to signon.
This is to prevent issues where a content designer previews a step
by step (which sets the cookie), then indirectly view some other
draft content (without a token in the URL), thereby falling back on
the cookie token which is not compatible with that particular draft
content. Prior to storing tokens as a cookie, the user would be
redirected to signon, so by storing tokens as a cookie, we'll have
caused a regression. This PR keeps the behaviour as it was.
Trello: https://trello.com/c/wAcvEyKm/143-change-authenticating-proxy-access-logic-to-consider-users-signed-in-and-have-an-auth-bypass-token
=> Authenticate user if not logged in and token is rejected

README.md, lib/proxy.rb, spec/lib/proxy_spec.rb, spec/requests/proxying_spec.rb
authenticating-proxy used to work on an either/or basis: logged in
users with a JWT token would not have any authentication information
proxied, so if the JWT token is invalid/expired/unauthenticated, they
would not be able to access the content, even if they are otherwise
authorised to do so.
This risked causing confusion when we come to implement persisting
tokens as a cookie, as authenticated users would have little idea
that the token is being used rather than their authentication.
Trello: https://trello.com/c/wAcvEyKm/143-change-authenticating-proxy-access-logic-to-consider-users-signed-in-and-have-an-auth-bypass-token
=> Proxy both authentication information and JWT token information

README.md
Removes reference to old 'startup.sh' file which no longer exists.
Provides instructions for OSX users to follow in absence of a
govuk-docker service for authenticating-proxy.
=> Updates documentation for setup/testing authenticating-proxy

config/mongoid.yml
This is so this app can be adapted for GOV.UK Docker usage.
=> Set up environment variables for mongo

config/mongoid.yml, lib/proxy.rb
This introduces a couple of fixes to allow this app to work in GOV.UK Docker.
First it fixes the mess I made with https://github.com/alphagov/authenticating-proxy/pull/166 - sorry
And introduces a variance on the change that was reverted in https://github.com/alphagov/authenticating-proxy/commit/aad8d6d75bac0c336195e434d43049969d75a35b#diff-de4c13211691eb0fbfe4b0e1f627a638 and explains why this is needed still.
=> Fixes for GOV.UK Docker

README.md
It was news to me that this was not encrypted and the data could actually be decoded and read by anybody. I've not got any evidence that we've used these tokens for sensitive data but feel it's prudent to leave a note for others so they don't then use this to include sensitive information.
=> Add note about JWT not being encrpyted

Jenkinsfile
We're using Amazon DocumentDB in Production, which apparently is
compatible with MongoDB 3.6, so use the version closest to this of
MongoDB for testing.
=> Use MongoDB 3.2 for testing

Jenkinsfile
As this matches what's used in Production. I did think before that
Authenticating Proxy was using Amazon DocumentDB, but this was just
because I missed that it was using the MongoDB 2.4 instances on the
router_backend machines.
=> Use MongoDB 2.4 for tests

README.md
This reflects that the guidance on using a user id as an issuer wasn't
representative of the common usage of the field - which is more
commonly used to represent an organisation. Including the user id also
potentially opens up some privacy concerns depending on interpretation
of legislation regarding private ids. The simplest approach is to
remove this value and only consider adding it to guidance when we have
evidence that it is important.
This also updates the definition of the subject to refer to how it
should be unique for an edition of a piece of content, which
differentiates it from some current usages where the same one is used
for all editions.
It also includes the usage of content_id which is suggested to help
identify any tokens that go astray. I'm hoping the combination of …
=> Remove issuer documentation; add content_id

config/initializers/gds_sso.rb
This file is no longer required as the latest release of the gds-sso gem sets these defaults itself ref: alphagov/gds-sso#241
=> Remove redundant GDS SSO initialiser

config/routes.rb, spec/requests/healthcheck_spec.rb
It ensures that the app is able to talk to the Mongo database. This also makes it closer to enabling CD for this app.
=> Improve healthcheck using govuk_app_config

README.md, docs/generating-a-token.md
https://trello.com/c/Psf7EzPB/204-move-away-from-startupsh
Depends on: https://github.com/alphagov/govuk-docker/pull/478
This follows the pattern established in [1].
[1]: https://github.com/alphagov/content-publisher/pull/2257
=> Rewrite README to favour GOV.UK Docker

lib/proxy.rb
authenticating-proxy checks that a user is logged in and, if so,
proxies their request to the draft stack.  If the user isn't logged
in, they get redirected to signon to authenticate.
This doesn't work for healthcheck requests, because they need to be
handled by the app.  So there's a check for whether the user is
requesting "/healthcheck".
406106d added a couple more healthcheck routes, so those also
need including in the check.
---
[Trello card](https://trello.com/c/tl6RV1el/723-improve-govuk-healthchecks)
=> Don't proxy RFC 141 healthcheck paths

Dockerfile, Procfile
We add a rudimentary Dockerfile to be able to test the integration
of the authentication-proxy app in the draft stack of the new
GOV.UK ECS platform.
It is not intended for this Dockerfile to be used in Production,
this will be done after this [work](https://trello.com/c/GMS8H1bN/426-building-containers-documenting-follow-up) is completed.
This Dockefile was tested by building the image and testing it with
govuk-infrastructure [PR](https://github.com/alphagov/govuk-infrastructure/pull/251)
Ref:
1. [task trello card](https://trello.com/c/vYNGbJSN/493-add-authenticating-proxy-to-the-draft-stack)
⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merge-your-own-pull-request) ⚠️
=> Add basic Dockerfile to integrate app in GOV.UK ECS

.github/workflows/ci.yaml, .github/workflows/deploy.yaml, Gemfile, Gemfile.lock, config/environments/test.rb, spec/spec_helper.rb
This workflow enables CI (tests, linting and security checks) using GitHub Actions. This apart of work to migrate the CI process from Jenkins to GitHub Actions. This doesn't migrate end to end tests as they've been deprecated. This also doesn't contain the process for creating a new release - this remains the responsibility of Jenkins. We needed to migrate the tests as we should be running tests on merge commit on the main branch before deploy them to our new infrastructure.
=> Enable CI in GitHub Actions

Dockerfile
govuk-ruby-base [already includes libpq5](https://github.com/alphagov/govuk-ruby-images/blob/f04f773/base.Dockerfile#L131), which is the package that directly [contains the Postgres client shared library](https://packages.ubuntu.com/jammy/amd64/libpq5/filelist).
[libpq-dev](https://packages.ubuntu.com/jammy/libpq-dev) indirectly installs the shared lib but its main purpose is to install the [headers and so on](https://packages.ubuntu.com/jammy/amd64/libpq-dev/filelist), which are not needed at runtime. As a rule of thumb, `-dev` packages in general should not be necessary at runtime.
This saves significant time and resources at build-time because we no longer have to fetch the entire APT catalogue on each build stage.
Reverts c1bf90b; fixes a build-time performance regression introduced …
=> Avoid installing unnecessary libpq-dev package.

lib/proxy.rb
This ensures we pass on the original domain to Rails in the X-Forwarded-Host, which is used by the redirect_to methods in Rails frontend applications to generate redirect URLs. This is needed by pages such as simple smart answers, as Rails redirects user to the next applicable page. Previously, this was broken because frontend Rails only had the Host header to generate redirect URLs and this was being set to the internal domain 'draft-router'.
Tested in integration.
=> Add X-Forwarded-Host header

app/models/user.rb, config/application.rb
These changes preemptively avoid two deprecation warnings that appear when we upgrade to Rails 7.1:
> DEPRECATION WARNING: Passing the class as positional argument is deprecated and will be removed in Rails 7.2.
and
> DEPRECATION WARNING: `Rails.application.secrets` is deprecated in favor of `Rails.application.credentials` and will be removed in Rails 7.2. (called from block in <class:Application> at /govuk/authenticating-proxy/config/application.rb:32)
=> Prepare for upgrade to rails 7.1

config/application.rb
Raising an exception on open redirects is the [default behaviour in Rails 7][1]. We disabled it in ad01e1c5d6703e35b591bb349a69bdd0e4f4d5f2 (15 Mar 2022) with a comment saying:
> allow open redirects, necessary for SSO
My guess is that this was required for the `/auth/gds/sign_out` path provided by gds-sso as that path redirects to Signon (i.e. a different host). The gds-sso Gem was updated in [PR 250][2] (merged on 29 Mar 2022) to explicitly allow redirecting to a different host in `/auth/gds/sign_out`. I believe that change in gds-sso means we can safely remove this line.
I've checked that signing in and out continues to work as expected with this line removed.
I think the only risk of something breaking with this change is if `session["redirect_to"]` somehow contained a URL and not …
=> Enable exceptions on open redirects

Dockerfile
This was missed in #515 and I think it means we haven't actually been running the app on v3.2.2 after that PR was merged.
c.f. https://github.com/alphagov/signon/pull/2588
=> Upgrade Ruby v3.1.2 -> v3.2.2 in Dockerfile

.github/dependabot.yml
I saw that @brucebolt had added this to a number of other repos (e.g. https://github.com/alphagov/collections/pull/3495) and thought it made sense to add it here too.
More information in the [GitHub Docs][1].
[1]: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
=> Configure dependabot to monitor GitHub Actions

lib/proxy.rb
The `rewrite_response` method is expecting an array for the body.
This was missed in https://github.com/alphagov/authenticating-proxy/pull/929 and resolves https://govuk.sentry.io/issues/5861864165/.
=> Put response body in array
